### ISSUE TITLE
How to define size in pixels?

### ISSUE THREAD

**Issue by MaslovD** [codebude/QRCoder#300] opened 2021-05-26 22:29 UTC
## Type of issue
[ ] Bug  
[ +] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement

**Comment by codebude** [comment] 2021-05-27 07:25
If you want to set a "fixed" size in terms of x*y pixels, you can work it out by setting the "pixelsPerModules" parameter. If your QR code has 20 modules (module=black/white "block") and you set "pixelsPerModule" to 10, then you will get a QR Code graphic with a size of 200*200px.

So to fix the size, generate the QR code data, check how much modules it has and then set "pixelsPerModules" to targetSizeInPx / moduleCount

You can read mroe about it here: https://github.com/codebude/QRCoder/issues/151#issuecomment-435821433

**Comment by project-zebra** [comment] 2021-06-01 15:19
thanks for answering my question, the problem is that I need exact size - but pixelsPerModules is integer, so I cannot set it to 2.3 or something , right? any recommendations?

**Comment by codebude** [comment] 2021-06-01 21:03
You could use the version parameter of the QRCodeGenerator to set a fixed version. (A version defines how much black and white modules are used to encode the data.) By choosing a version which has X modules per row, whereby target size in px / version modules X results in a pixelsPerModules value without fraction, you could achieve your expected result. 

The thing is: if you use fixed version, you have to ensure tool chose a version which is high enough to store your payload and at the same time as small as possible to raise the readability of the QR code. 
If you don't use a fixed version, the generator will pickup the best version for you. So one approach would be to encode the payload, then read the version number from the qrcode data object and use this version number as a starting point for finding the next bigger version, that fulfills the requirement (target size / modules per row....) described above.

**Comment by codebude** [comment] 2021-11-08 19:49
Closing this, because no code changes needed. (Only question about usage/handling, which was answered.)

**Closed by codebude** 2021-11-08 19:49 UTC
Labels: question
