### ISSUE TITLE
QR code image generated using this library does not contain string value at the bottom of QR code image.

### ISSUE THREAD

**Issue by nomantalish** [codebude/QRCoder#143] opened 2018-10-06 18:22 UTC
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[ ] Request for new feature/improvement

**Comment by codebude** [comment] 2018-10-10 14:00
Hi @nomantalish ,

can you please give an example or more information? It isn't clear to me, what the problem is about...

**Comment by Ruffio** [comment] 2018-11-02 08:48
@nomantalish what is the issue? Can you show a sample of the issue?

**Comment by codebude** [comment] 2018-11-05 10:12
Since there is no feedback and no clear description of the problem, I'll close this issue. Feel free to re-open it, @nomantalish , if you can provide more information.

**Closed by codebude** 2018-11-05 10:12 UTC
