### ISSUE TITLE
QRCoder Reader

### ISSUE THREAD

**Issue by RoyLaiYi** [codebude/QRCoder#342] opened 2021-11-11 03:09 UTC
## Type of issue
[ ] Bug  
[ ] Question (e.g. about handling/usage)  
[x] Request for new feature/improvement  

## Expected Behavior

Can get QRCoder details by passing a image.

## Current Behavior

Can only generate but can not read.

**Comment by codebude** [comment] 2021-11-11 21:51
Hi @RoyLaiYi ,
QRCoder was designed and implemented as generator, not as decoder/reader. Right now there no such functionality and implementing such functionality would be a huge amount of work.
I'm not closing this issue, because I see that there might be an interest, but I won't promise that such feature will be implemented in the near future. 

If some wants to take the challenge and send in a PR feel free. If it's coded well, I'll merge it. But my own resources aren't enough to get this job done soon.

**Comment by codebude** [comment] 2024-04-27 21:43
2.5 years later nothing has changed. Neither on my opinion nor on my available resource. Thus I'll close the issue for now.

**Closed by codebude** 2024-04-27 21:43 UTC
Labels: idea, help-wanted
