### ISSUE TITLE
Linux system loading icon generates qrcode error

### ISSUE THREAD

**Issue by dazsco** [codebude/QRCoder#124] opened 2018-05-20 09:48 UTC
eg:
`Bitmap bp = qrCode.GetGraphic(20, Color.Black, Color.White,
                            (Bitmap)Image.FromFile(Path.Combine(_hostingEnvironment.WebRootPath, "Common/Images/", "pay.png")),10);`

System.ArgumentException: Parameter is not valid.
at System.Drawing.Graphics.FillRegion(Brush brush, Region region)
at QRCoder.QRCode.GetGraphic(Int32 pixelsPerModule, Color darkColor, Color lightColor, Bitmap icon, Int32 iconSizePercent, Int32 iconBorderWidth, Boolean drawQuietZones)
at Daz.Tau.Web.Controllers.PaymentControllerBase.RenderQrCode(String str) in D:\Repos\TaurusCore\src\Daz.Tau.Web.Core\Controllers\PaymentControllerBase.cs:line 58
at Daz.Tau.Web.Controllers.PaymentControllerBase.ScanCodeGen(String code) in D:\Repos\TaurusCore\src\Daz.Tau.Web.Core\Controllers\PaymentControllerBase.cs:line 34
at lambda_method(Closure , Object , Object[] )
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.&lt;InvokeActionMethodAsync&gt;d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.&lt;InvokeNextActionFilterAsync&gt;d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.&lt;InvokeInnerFilterAsync&gt;d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.&lt;InvokeNextExceptionFilterAsync&gt;d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.&lt;InvokeNextResourceFilter&gt;d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State&amp; next, Scope&amp; scope, Object&amp; state, Boolean&amp; isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.&lt;InvokeFilterPipelineAsync&gt;d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.&lt;InvokeAsync&gt;d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Builder.RouterMiddleware.&lt;Invoke&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.&lt;Invoke&gt;d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.&lt;Invoke&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Abp.AspNetZeroCore.Web.Authentication.JwtBearer.JwtTokenMiddleware.&lt;&gt;c__DisplayClass0_0.&lt;&lt;UseJwtTokenMiddleware&gt;b__0&gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.&lt;Invoke&gt;d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.&lt;Invoke&gt;d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Abp.AspNetCore.Security.AbpSecurityHeadersMiddleware.&lt;Invoke&gt;d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.&lt;Invoke&gt;d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.&lt;ProcessRequestsAsync&gt;d__2.MoveNext()

do not load icons to run
eg:
`Bitmap bp = qrCode.GetGraphic(20);`

**Comment by codebude** [comment] 2018-05-24 06:13
Hi @dazsco ,

I created a small .NetCore commandline app which just generates a QR code with an image:

``` csharp
using QRCoder;
using System;
using System.Drawing;

namespace QrNetCore
{
    class Program
    {
        static void Main(string[] args)
        {
            var img = WriteQRImage("SomeDataToQR", 20, @"C:\Users\RCC-Herrmann\Pictures\NYC\asd.JPG");
            img.Save(@"C:\Users\RCC-Herrmann\Pictures\NYC\asd2.JPG");
            Console.WriteLine(img.Width + "x" + img.Height + "px");
            Console.ReadKey();
        }

        // ReSharper disable once InconsistentNaming
        public static Bitmap WriteQRImage(string data, int ppm = 20, string fpath = null)
        {
            using (var qrGenerator = new QRCodeGenerator())
            {
                using (var qrCodeData = qrGenerator.CreateQrCode(data, QRCodeGenerator.ECCLevel.Q))
                {
                    using (var qrCode = new QRCode(qrCodeData))
                    {
                        if (fpath == null)
                        {
                            return qrCode.GetGraphic(ppm);
                        }
                        else
                        {
                            return qrCode.GetGraphic(ppm, Color.Black, Color.White, (Bitmap)Image.FromFile(fpath), 25);
                        }
                    }                    
                }
            }
        }
    }
}
```

The app executes without any problems on Windows as also on an Ubuntu Linux machine. So in general the library seems to work, which means that there's probably either a problem with your code or your system environment.

- Have you checked if the path in your code (`Path.Combine(_hostingEnvironment.WebRootPath, "Common/Images/", "pay.png")`) points to a valid image file? 
- Have you checked if the Bitmap object is created correctly?
- Which Linux distro and version do you use in your environment?
- Which .NET Core version do you use in your environment? 

(Hint: For my successful test of the above app, I installed the current .NET Core release on Ubuntu by use of the following commands:
``` bash
~$ wget -q packages-microsoft-prod.deb https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
~$ sudo dpkg -i packages-microsoft-prod.deb
~$ sudo apt-get install apt-transport-https
~$ sudo apt-get update
~$ sudo apt-get install dotnet-sdk-2.1.200
```

After this commands I copied my .NET core project to the Linux server, `cd`'d into the project dir and ran the app with `dotnet run`.)

**Comment by codebude** [comment] 2018-06-03 18:06
Hi @dazsco ,

any feedback? Could you solve your problems?

**Comment by dazsco** [comment] 2018-06-06 17:30
@codebude  
I'm sorry to go out for a while. I am using it in CentOS 7.2, .net core 2.0. Now it is upgraded to .net core 2.1 and I get an error.

System.ArgumentException: Parameter is not valid.
   at System.Drawing.Graphics.FillRegion(Brush brush, Region region)
   at QRCoder.QRCode.GetGraphic(Int32 pixelsPerModule, Color darkColor, Color lightColor, Bitmap icon, Int32 iconSizePercent, Int32 iconBorderWidth, Boolean drawQuietZones)
   at Daz.Tau.Web.Controllers.PaymentControllerBase.RenderQrCode(String str) in D:\Repos\TaurusCore\src\Daz.Tau.Web.Core\Controllers\PaymentControllerBase.cs:line 58
   at Daz.Tau.Web.Controllers.PaymentControllerBase.ScanCodeGen(String code) in D:\Repos\TaurusCore\src\Daz.Tau.Web.Core\Controllers\PaymentControllerBase.cs:line 34
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()

```
private Bitmap RenderQrCode(string str)
        {
            using (QRCodeGenerator qrGenerator = new QRCodeGenerator())
            {
                using (QRCodeData qrCodeData = qrGenerator.CreateQrCode(str, QRCodeGenerator.ECCLevel.L))
                {
                    using (QRCode qrCode = new QRCode(qrCodeData))
                    {
                        Bitmap bp = qrCode.GetGraphic(20, Color.Black, Color.White,
                            (Bitmap)Image.FromFile(Path.Combine(_hostingEnvironment.WebRootPath, "Common/Images/pay.png")), 10);
                        return bp;
                    }
                }
            }

        }
```

**Comment by codebude** [comment] 2018-06-07 06:38
Since I can't reproduce the error, I can only assume what's going wrong. But maybe it's a GDI+ error. Have you tried to update your libgdiplug binaries on CentOS? It should work like described here: https://unix.stackexchange.com/questions/362984/how-to-install-libgdiplus-on-centos-7

**Comment by Ruffio** [comment] 2018-11-02 08:49
@dazsco have you tried @codebude suggestion? Did it resolve your issue?

**Comment by codebude** [comment] 2018-11-12 08:50
Since there seems to be no further interest by the issue owner, I'll close this one. Feel free to re-open it, when there is an actual need.

**Closed by codebude** 2018-11-12 08:50 UTC
Labels: question
